### PR TITLE
Fixes bugs in streaming output from started program back to Notepad++

### LINKED ISSUE #10: The Plugin only reads 1024 bytes from the pipes to the program started by the plugin
The Plugin only reads 1024 bytes from the listener pipes to the program started by the the plugin.

I guess this is due to [this](https://github.com/npp-plugins/pork2sausage/blob/a14648bf449f3ce37fa1b703acdea217d1e5c045/src/Process.cpp#L238) codeblock in the routine to read from the pipe to _StdOut_ of the started program. There is a similar code block [here](https://github.com/npp-plugins/pork2sausage/blob/a14648bf449f3ce37fa1b703acdea217d1e5c045/src/Process.cpp#L293) for reading the pipe to _StdErr_ of the started program.

### LINKED ISSUE #14: The plug-in gives error with text in Chinese when processing text with Python
I installed Pork2sausage plug-in and decided to check how it goes along with Python. So, I created the following pork2sausage.ini file:
[Python]
progPath=C:\Users\Sergey\AppData\Local\Programs\Python\Python39\python.exe
progCmd=python $(SELECTION)
workDir=C:\Users\Sergey\AppData\Local\Programs\Python\Python39\

Should I select 3+2 and give command to make the sausage, I have got error message with text in Chinese, depicted at the screen-shot.

Screen-shot_2021-03-19_17-32-46

I would appreciate some one telling me what is wrong with my ini-file (really, I have no clue about it, everything seems to be correct) and what this message means.

@donho You may want to consider replacing the Chinese text with its English equivalent. And the last, but not the least, thank you very much for great text editor.

### PR DESCRIPTION
**Pull request by dinkumoil**
Fix: The Plugin only reads 1024 bytes from the pipes to the program started by the plugin.
Fix: Converting bytes read from StdErr pipe to string doesn't consider Unicode build.

Fixes #10 
Fixes #14

### CODE REVIEW

**Comment by dinkumoil** [comment]
@donho 

I want to remind you for this PR and the problems it fixes. Maybe now (after overcoming the most problems with Npp Plugins Manager) you have more time for this sideshow.

**Comment by dinkumoil** [comment]
@donho 

Another try to bump this PR. If you don't like it, please leave a comment at least.

**Comment by dinkumoil** [comment]
@donho 

Another try to bump this PR. If you don't like it, please leave a comment at least.

**Comment by donho** [comment]
oups! Sorry, just saw your PR. I'll check it now.

**Comment by donho** [comment]
@dinkumoil 
**Without applying your PR**, I've got a crash with pork2sausage plugin (with Notepad++ v8 RC2).

What's your Notepad++ version?

**Comment by dinkumoil** [comment]
@donho 

I tested with

* a fresh portable install of Npp 8.0 RC2, downloaded using the link you provided in the community forum.
* your release of _PorkToSausage_ v2.1 plugin, downloaded from your repo.

No crash.

Contains your _pork2sausage.ini_ the correct path to your external converter? What commands did you execute?

**Comment by donho** [comment]
I identified the crash cause due to an old config.xml, but I erased the file in question by accident.
So I guess I'll let it go utile next time I reproduce the crash.

**Pull request closed without merging**
